name : action workflow

on: workflow_dispatch

jobs:
  run-js-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      
      - name: js action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Guns N Roses
        
      - name: log time
        run: echo "${{ steps.greet.outputs.time }}"
        
      - name : run commands
        run: |
          pwd
          ls -al
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo ${{ github.token }}
          
