name: environment workflow

on: workflow_dispatch

env:
  WF_ENV: workflow env variable
  
jobs:

  first-job:
  
    runs-on: ubuntu-latest
    env:
      JOB_ENV: ${{ secrets.job_env }}
    steps:
      - name: log env
        env:
          STEP_ENV: step env variable
        run: |
          echo "workflow env: ${WF_ENV}"
          echo "job env: ${JOB_ENV}"
          echo "Step env: ${STEP_ENV}"
          
      - name: log env2
        run: |
          echo "workflow env: ${WF_ENV}"
          echo "job env: ${JOB_ENV}"
          echo "Step env: ${STEP_ENV}"
          
  second-job:
  
    runs-on: ubuntu-latest
    steps:
      - name: log second job event
        run: |
          echo "GITHUB Workflow: ${GITHUB_WORKFLOW}"
          echo "GITHUB Action: ${GITHUB_ACTION}"
          echo "GITHUB Actions: ${GITHUB_ACTIONS}"
          echo "GITHUB Repository: ${GITHUB_REPOSITORY}"
          echo "GITHUB workspace: ${GITHUB_WORKSPACE}"
          echo "workflow env: ${WF_ENV}"
          echo "job env: ${JOB_ENV}"
          echo "Step env: ${STEP_ENV}"
          
        