name: section2_2 workflow

on: workflow_dispatch
#  push:
#    branches:
#      - master
 #     - 'feature/*'
 #     - 'feature/**'
 #     - '!feature/featC'
#    branches-ignore:
#      - develope
 #   tags:
      - v1.*
 #   paths:
      - '**.js'
#    paths-ignore:
#      - 'Docs/**'
      
jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
      - name: building it
        run: |
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT