name: Own Excutable

on: push

jobs:
  own-exec:
    runs-on: ubuntu-latest
    container: 
      image: node:10.18.0-jessie
    steps:
      - name: node version
        run: node -v
        
      - name: checkout code
        uses: actions/checkout@v1
        
      - name: step container with own exec
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: ./script.sh
          args: 'First argument'
          