name: section 2 workflow

on: 
  push:
  pull_request:
    types: [closed]

jobs:
  
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo $GITHUB_EVENT_NAME
          echo $GITHUB_REPOSITORY
          
      - name: printing the environments variables
        run: printenv | grep GITHUB
      
