name: section 2 workflow

on: repository_dispatch
#  push:
#  pull_request:
#    types: [closed]
#  schedule:
#   - cron: "0/5 * * * *"
#    - cron: "0/6 * * * *"


jobs:
  
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo $GITHUB_EVENT_NAME
          echo $GITHUB_REPOSITORY
          
      - name: printing the environments variables
        run: printenv | grep GITHUB
      
