name: continue on error

on: workflow_dispatch

jobs:
  run-on-error:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: error steps
        run: eecho "error"
        timeout-minutes: 1
        continue-on-error: true
      
      - name: job context
        run: echo $JOB_CONTEXT
        env: 
          JOB_CONTEXT: ${{ toJSON(job) }}
         
      - name: steps context
        run: echo $STEP_CONTEXT
        env:
          STEP_CONTEXT: ${{ toJSON(steps) }}
          