name : matrix workflow

on : workflow_dispatch

jobs:
  node-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [6, 7, 8]
      fail-fast: true #by default it is true, if any job fail others will stop
      max-parallel: 2
    steps:
      - name: log node version
        run: node -v
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 6
      - name: log node version
        run: node -v          