name : simple workflow
#simple workflow for testing
on : [workflow_dispath]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo 
        run : echo "hello world"
        shell: sh
        
      - name : check versions
        run: |
          docker version
          mvn --version
          echo JAVA_HOME
  run-windows-command:
    runs-on: windows-latest
    needs: [run-shell-command]
    steps:
      - name : directory power shell
        run: Get-Location
        
      - name: directory bash
        run : pwd
        shell: bash
        
  run-another-shell:
    runs-on: ubuntu-latest
    needs: [run-shell-command]
    steps: 
      - name: just pwd
        run: pwd
        