name : simple workflow
#simple workflow for testing
on : [push]

jobs:
  simple-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo 
        run : echo "hello world"
        shell: sh
        
      - name : check versions
        run: |
          docker version
          mvn --version
          echo JAVA_HOME
        